### ISSUE TITLE
Add-AppxPackage : Deployment failed with HRESULT: 0x80072EFE, The text associated with this error code could not be found

### ISSUE THREAD

**Issue by yoku-nai-desu** [WinApps-share/WinApps-bucket#7]
I'm not sure if this error is related to my env or is it a packaging issue or something else, I'm hoping to get some advice as for where to go from here...mentioned note in the error output isn't helping much...thanks in advanced

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80072EFE, The text associated with this error code could not be
found.
Error message string not found
Appinstaller operation failed with error code 0x80072EFE. Detail: Unknown error
NOTE: For additional information, look for [ActivityId] ba0c5a61-b587-0000-80f4-43ba87b5da01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID ba0c5a61-b587-0000-80f4-43ba87b5da01
At line:5 char:1
+ Add-AppxPackage -AppInstallerFile "$dir\files.appinstaller"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\f\scoo...es.appinstaller:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by yoku-nai-desu** [comment]
im guessing some sort of problem with appinstaller or microsoft store, since appinstaller file downloads Files and isn't a complete .appx

and downloading .appinstaller from official website seems to be working as intended....

**Comment by 007ayong** [comment]
Thank you for reporting this issue. 

The error code 0x80072EFE you're encountering is typically related to network connection problems.

**Comment by 007ayong** [comment]
@yoku-nai-desu  Hello friends, I have updated the installation package download link from `.appinstaller` to `.msixbundle`.

In this way, there is no need to connect to the Internet to download when executing the `Add-AppxPackage` command, which should most likely solve your problem.

I hope you can try it again and look forward to your reply.

**Comment by yoku-nai-desu** [comment]
@007ayong thanks a bunch, much appreciated!
